@startuml
class ConsoleIO {
    + WriteLine(message:string) : void
    + Write(message:string) : void
    + ReadLine() : string
    + ReadKey(b:bool) : ConsoleKey
    + KeyAvailable() : bool
}
IConsoleIO <|-- ConsoleIO
@enduml
